apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-gateway.fullname" . }}
  labels:
    {{- include "metrics-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "metrics-gateway.selectorLabels" . | nindent 4 }}
